server:
  undertow:
    io-threads: 2
    worker-threads: 30
    accesslog:
      dir: logs/access/
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D "%{i,Referer}" "%{i,User-Agent}"'
      prefix: ${spring.application.name}_access
      suffix: log
      rotate: true

# 加解密根密码
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Spring 相关
spring:
  jackson:
    default-property-inclusion: non_null

http:
  maxTotal: 2000
  defaultMaxPerRoute: 2000


logging:
  level:
    custom.*: DEBUG