custom-config:
  server-addr: ENC(e2i3gVIrfKPf7BGc1QY18HQlsyE7JSg/3BRsZ8TwXHewvOw5o1SHUhDbtk1hb+rZfOtzDXZGXGpcz5fiUgBuaw==)

server:
  port: 9999

common:
  core:
    kaptcha:
      width: 100
      height: 40
      charLength: 4
      charSpace: 2
      fontColor: black
      fontSize: 32

# Spring 相关
spring:
  cloud:
    gateway:
      routes:
        - id: thirdparty_route
          uri: lb://EC-THIRDPARTY-SERVICE
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'cgroup@123456789'

reactor:
  netty:
    ioWorkerCount: 12
    http:
      server:
        accessLogEnabled: true

