custom-config:
  server-addr: ENC(e2i3gVIrfKPf7BGc1QY18HQlsyE7JSg/3BRsZ8TwXHewvOw5o1SHUhDbtk1hb+rZfOtzDXZGXGpcz5fiUgBuaw==)

server:
  port: 9999

common:
  core:
    kaptcha:
      width: 100
      height: 40
      charLength: 4
      charSpace: 2
      fontColor: black
      fontSize: 32

# Spring 相关
spring:
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 60000
      locator:
        enabled: true
      default-filters:
        - RemoveRequestHeader=from
        - StripPrefix=1
      routes:
        - id: custom_basic
          uri: lb://CUSTOM-BASIC-SERVICE
          predicates:
            - Path=/basic/**

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'cgroup@123456789'

reactor:
  netty:
    ioWorkerCount: 12
    http:
      server:
        accessLogEnabled: true


