custom-config:
  server-addr: ENC(e2i3gVIrfKPf7BGc1QY18HQlsyE7JSg/3BRsZ8TwXHewvOw5o1SHUhDbtk1hb+rZfOtzDXZGXGpcz5fiUgBuaw==)

# 加解密根密码
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Spring 相关
spring:
  mvc:
    async:
      request-timeout: 20
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  cloud:
    gateway:
      routes:
        - id: thirdparty_route
          uri: lb://EC-THIRDPARTY-SERVICE
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://EC-WARE-SERVICE
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://EC-MEMBER-SERVICE
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://EC-PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://EC-ADMIN-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/ec-admin/$\{segment}

logging:
  level:
    root: debug
    custom.*: debug
    common.*: debug