server:
  max-http-header-size: 10000000
  undertow:
    io-threads: 2
    worker-threads: 3000
spring:
  profiles:
    # this sequence is master
    include: common-dev,redis-dev,actuator-dev,oss-dev,uid-dev,common
  datasource:
    username: ENC(3+5Pg+H9L0s1ATmg/xTWLbNt9OeMFguochuRyTl9a4BGbD4lL2SLM8351rdHYhC2)
    password: ENC(MkGdNTchUL+OnF+nvm5YSSjWc7XeHLNab+KV9Wr3fqF1fAbEVLB2urZotLn8nAk1)
    url: ENC(0v+NkGIx3AZzSh9buMDveJVdOwce6hQBoDxMo5bOnJhYyN01d6Gdmb9DcxOKlpzxCUP+PVLfZx46zfA0Qk49j899H/o6/Sfcmn+HQGKcrDdQji5C/R2PvyNvjw3tNuePNEN9NCLBzfH9M5XNk3MW67dztd4c7VQrISeY45yctuult/+YRb6Uy5oQZscMeLumvp3ADuTLP0A/HgOWQxv50WOLjEOOK2HKHmJjTvrgYkIpmnPbDXDG/NxI2Ckg/nklL11rw0JoEJkGcgk0jilmu4N1l9G8KpfoK36wc0xZi13IP81UMNhO9/iUQtX19GtSxc+VEuKuLg6onHHnacYVQa/yAqdhImEdHy5+/VVH64+x/lfoT39gfoOg1307qERNWXP11a9SQNkrqr4IPn7+B9AdOi6bOpmXnnNFO6LJn/OYT2GsgeSK5m0SgIW3AgWD)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      register-mbeans: true
common:
  core:
    redis:
      module: common

# mybatis-plus
mybatis-plus:
  # typeEnumsPackage: boot.mybatis.common.constants.enums
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

