swagger3:
  enable: true
  author: springfox
  email: springfox@io.com
  groupName: ${spring.application.name}
  tryHost: http://localhost:${server.port}
  applicationName: ${spring.application.name}
  version: 1.0
  applicationDescription: api doc

