common:
  oss:
    aliyun:
      enable: true
      accessKey: ENC(Kf42+pHi8/IU/QWZlOm8UpTTLIMxHWRBWkYENv7a1hO93AkB/rb0G9juNLPXSAfpzYVkX4DGFvUKC1qLooR9Yw==)
      accessKeySecret: ENC(zu07F3mfQ5SeGQR2YG3q7OWoRMoJPE73C5DWwqxV8LWyz8MOGpz0viKcdadOBeS/Gp54+V0LWWC8jjWIoVTbnA==)
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: ENC(xJHHZLCs0MUV7V9RH7Mc4Cn8foAUYQHk4pQ5tdVuU1EEqRF2sZjk57O61kYYTy04)
      cdnHost:
      host:
      exportPath: "file/download/export/"
    tencent:
      enable: true
      accessKey:
      accessKeySecret:
      bucket:
      cdnHost:
      host:
      exportPath: "file/download/export/"
      region:
      durationSeconds: 1800
