server:
  max-http-header-size: 10000000
  undertow:
    io-threads: 2
    worker-threads: 3000
spring:
  profiles:
    # this sequence is master
    include: common-dev,redis-dev,actuator-dev,oss-dev,uid-dev,common
  datasource:
    username: ENC(3+5Pg+H9L0s1ATmg/xTWLbNt9OeMFguochuRyTl9a4BGbD4lL2SLM8351rdHYhC2)
    password: ENC(MkGdNTchUL+OnF+nvm5YSSjWc7XeHLNab+KV9Wr3fqF1fAbEVLB2urZotLn8nAk1)
    url: ENC(tr7Y7YBoxxrIVogMNB8sF/Zi+6un98RlW0/ZcmyeyI6pxuHX0PC22O3Sq0ba9visDYIbCoMli55ClnRGXS0EWP0cJp0yr/tMm9qESfbDopa2KNaWG6O16jHi2l5L9S6T4rEjaWi58TyzM5EwEp4Nrs4uGMrOuIlrAaCzs10vN+Hu4n7bcux/QGOoqspTruTXddfVdZMAn11H7GLw/Pp4FYe/ukGgHMsxiScqPwnnsEXxvcDGWofWOjHs0t0DK2ElfbWrMsThwZOVSIKfXOYroZgW6a3SOk0YTt4lBIG88BgV4GuUYePuP3WFYrsla1dk+b6DVfYAXzrmA9+51AXG5mq68pga5dzSKnCKZ6MXcOyeLQs2/bNYn0qCcQLCIaJQrOgjgIQUehrMxiIp6XLUORQRZGUiS800DnvHaELikKuS/opfg7vGr9pEBNudnRFt)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      register-mbeans: true
common:
  core:
    redis:
      module: common

# mybatis-plus
mybatis-plus:
  # typeEnumsPackage: boot.mybatis.common.constants.enums
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

