custom-config:
  server-addr: ENC(e2i3gVIrfKPf7BGc1QY18HQlsyE7JSg/3BRsZ8TwXHewvOw5o1SHUhDbtk1hb+rZfOtzDXZGXGpcz5fiUgBuaw==)

server:
  port: 3333
  undertow:
    io-threads: 2
    # undertow:   worker(availableProcessors() * 8), queue(N/A)
    # tomcat:     worker(200), queue[负载高峰(恢复时长)](100)
    worker-threads: 30
    accesslog:
      dir: logs/access/
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D "%{i,Referer}" "%{i,User-Agent}"'
      # prefix: ${spring.application.name}_access
      suffix: log
      rotate: true

# 加解密根密码
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Spring 相关
spring:
  mvc:
    async:
      request-timeout: 20
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    custom.*: debug
    common.*: debug

# 直接放行URL
common:
  core:
    ignore:
      ignoreMatchers:
        - antPattern: /actuator/**
        - antPattern: /v2/api-docs
          method: GET
        - antPattern: /basic/inner/**
        - antPattern: /basic/admin/**
        - antPattern: /basic/health/**
          method: GET

# grpc
grpc:
  server:
    # this will auto generate
    port: 0
  client:
    # this config can be customize, and used in @GrpcClient
    upms-service:
      # if no address config, will use client name
      address: 'discovery:///CUSTOM-UPMS-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT

