spring:
  config:
    name: custom-test

mybatis-plus:
  typeEnumsPackage: custom.constants.enums


logging:
  config: classpath:logback-spring.xml

common:
  core:
    global:
      handler:
        enabled: true
      request-id:
        enabled: true
        key: req-id
