jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 8080
  tomcat:
    accept-count: 500
    max-threads: 100
    min-spare-threads: 50
    max-connections: 5000

druid:
  spring:
    monitor:
      enable: false
      locations: com.sample.*

### mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 字段策略
      field-strategy: not_null
      # 驼峰下划线转换
      table-underline: true
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认 0、表示未删除）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  application:
    name: common-response-starter-test
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 45MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: ENC(/Kd/rkpLNkt8FWY4FaG75Ra/jZrcrdM/8pjKWKtbaY/WEhq8tc7PAOu5oDU8Mi5dN4EhnYMQ/uKIc6gS6/o/dHSTpZwDgQtFsyvAFUyd6yHOYvacy9WjpXgLHj0D8VjXTagiVDNh2sxwfEnB2d8y9tRqwt7i9sBzF6oNbzgQ8ed3xXhjFmjzlXpZGf3Tiank)
      username: ENC(uVs7DP260FXOKYBacQjLo7Fonyyiq2qwnSjOGt9Q2weCl3ceVf6c6VAAQ6WkTsUt)
      password: ENC(IkxnRsO4O+J/8pOvHoL7/9sSyvhq3Zv9AYObJx9ldt636qyRiBTGrwndtSISEY4F)
      initial-size: 10
      minIdle: 50
      maxActive: 500
      maxWait: 60000
      fail-fast: true
      Keep-alive: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 100
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        #访问路径为/druid时，跳转到StatViewServlet  http://127.0.0.1:8080/druid
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: ENC(1j3TT4M6aHscVzKpeHWX5KNKRU7ui1jesPGY52W2FEl9WunVIBiVizoeQv4ocWxd)
        login-password: ENC(Jm9wTCpswKDpVkuiT0JmwMiz7H4bqiOLnEK1Hs49QPrB+RJ4Y8pUh2ON4FPOSjNV)

logging:
  level:
    ec.*: debug

