swagger3:
  enabled: true
  ping: true
  author: alice52
  email: zzhang_xz@163.com
  group-name: ${spring.application.name}
  application-name: ${spring.application.name}
  version: 1.0
  application-description: api doc
  token-name: sa

spring:
  application:
    name: swagger-starter-test

