name: Build Image Project-Custom-Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'backend/project-cloud-custom/**'
      - '.github/workflows/docker-project-cloud-backend.yml'
  pull_request:

jobs:
  push-image:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[image]')"
    env: # define constant
      PROJECT_PREFIX: backend/project-cloud-custom
      IMAGE_PREFIX: practice

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Export Global Var
        run: |
          echo "ALI_DOCKER_REGISTRY=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_USERNAME=${{ secrets.ALI_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_PASSWORD=${{ secrets.ALI_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          echo "JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" >> $GITHUB_ENV
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV
          echo "TAG=`echo \`date +%Y%m%d\`.${GITHUB_SHA} | cut -c1-16`" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project-cloud-custom module
        run: |
          PROJECT_NAME=project-cloud-custom
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME
          cd common-api/ && ./reparent.sh && cd ../
          mvn clean package -DskipTests=true

      - name: Push project-cloud-custom-basic Image
        run: |
          MODULE_NAME_PREFIX=custom-basic
          MODULE_NAME=custom-basic-biz
          mkdir -p $PROJECT_HOME/$PROJECT_PREFIX/$MODULE_NAME_PREFIX/$MODULE_NAME/target
          mv custom-basic.jar $PROJECT_HOME/$PROJECT_PREFIX/$MODULE_NAME_PREFIX/$MODULE_NAME/target
          cd $PROJECT_HOME/$PROJECT_PREFIX/$MODULE_NAME_PREFIX/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}
