name: Build Project-Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/project-backend.yml'
  pull_request:
  workflow_call:

jobs:
  reusable_build_job:
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, '[image]')"
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env: # define constant
      PROJECT_PREFIX: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Export Global Var
        run: |
          echo "ALI_DOCKER_REGISTRY=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_USERNAME=${{ secrets.ALI_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_PASSWORD=${{ secrets.ALI_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          echo "JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" >> $GITHUB_ENV
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV
          echo "TAG=`echo \`date +%Y%m%d\`.${GITHUB_SHA} | cut -c1-16`" >> $GITHUB_ENV
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project-cloud-custom module
        run: |

          PROJECT_NAME=project-cloud-custom
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME
          rm ./common-api/pom.xml
          mv ./common-api/pom.xml.dev ./common-api/pom.xml
          mvn clean package -DskipTests=true

      - name: Upload Custom Basic Artifact
        uses: actions/upload-artifact@v2
        with:
          name: custom-basic.jar
          path: ${{ github.workspace }}/**/custom-basic-.*?.jar
          retention-days: 1

